distance:
	racket -y herbie.rkt report ../bench distance.fpcore ../infra/reports/distance
2sin2cos:
	racket -y herbie.rkt report ../bench/2sin.fpcore ../infra/2sin2cos
hamming:
	racket -y herbie.rkt report ../bench/hamming ../infra/reports/hamming
